### ISSUE TITLE
我尝试跑你的代码好像出了环境问题

### ISSUE THREAD

**Issue by cy-dream** [lytum/joint-intent-classification-and-slot-filling-based-on-BERT#2]
你的运行环境是什么

Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from joint_bert_model import JointBertModel
  File "E:\代码\joint-intent\joint_bert_model.py", line 5, in <module>
    from bert_model import BertLayer
  File "E:\代码\joint-intent\bert_model.py", line 3, in <module>
    import tensorflow.python.keras.backend as K
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation_wrapper.py", line 106, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: module 'tensorflow' has no attribute 'python'

**Comment by ohroffen** [comment]
我也碰到了同样的问题，Ubuntu环境下tensorflow版本为1.12.0，想请问作者是否是我的tensorflow版本不对？

**Comment by lytum** [comment]
我的是windows系统，tensorflow版本是1.14.0，你们试试我这个版本的tensorflow。

**Comment by ohroffen** [comment]
> 我的是windows系统，tensorflow版本是1.14.0，你们试试我这个版本的tensorflow。

更换tensorflow版本后问题解决了，谢谢！

**Comment by lytum** [comment]
我在自己的另外一台电脑上也出现了这个问题，我的解决方式是 把python3.5升级到了python3.7，tensorflow一直是1.14.0，所以应该就是环境的问题。
